name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-14
        python:
          - '3.09'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Check Formatting
        run: hatch fmt --check
      - name: Check Typing
        run: hatch run types:check
      - name: Run Test Coverage
        run: hatch run cov -v
      - name: Build
        run: hatch build
